"""
Help Window Module

This module provides a searchable help dialog for the SAR K9 Training Records application.
The help content is organized into sections that users can navigate and search.
An Index tab provides alphabetical access to key terms.

AUTO-GENERATED FILE - Do not edit directly!
Generated by generate_help_window.py from the help documentation Word file.
"""

import tkinter as tk
from tkinter import ttk
import re


# Help content organized by section
HELP_SECTIONS = {
    "SAR K9 Training Record Introduction": """This is a preliminary help file to get the user started.  This window can always be viewed by pushing F1 on your keyboard.  It is advised that the user read this entire document one time to get an idea of how to use the program.  However, it is not necessary to memorize it since tooltips pop up when hovering the mouse over most of the more complicated entries.""",

    "Setup": """• Select the primary storage folder.  The database and configuration files are saved here.  Click the **Browse** button and navigate to the location you wish to save this data.  On a modern Windows machine placing the folder either on a path included in Microsoft OneDrive or a Dropbox folder is recommended.  Then, in the event of a hardware failure, the training log can be recovered as soon as the hardware is repaired.
  • Click **on Initialize Data Structures** which creates an empty database. 
  • In a similar manner select a backup folder.  While optional, it is STRONGLY recommended to configure this.  Ideally, this folder should reside on an external hard drive or another service such as Google Drive or Dropbox.  This additional redundancy helps ensure that data is never lost.
  • Configure a PDF export folder.  This folder is used to export human readable logs suitable for certification or legal requirements.
  • Configure a folder for Excel compatible data files. While these files can be edited and used to update the database, no error checking is performed on those updates so any mistake in editing could corrupt the database.
  • Now enter training locations that will be used repeatedly. While not required, this shortcut will simplify data entry later.  To enter a location, either type in the name followed by **Enter** or click the **Add Location** button.
  • Dog names are entered in an identical manner.  Unlike location names, however, all dogs that are to be recorded must be entered here. Once used in a session, never delete or alter a dog name since it is possible to lose access to any sessions using a different name.
  • **Terrain Types** and **Distraction ****T****ypes** are entered in a similar manner.  The user can adjust the order they appear in the table as desired. The most commonly used entries should usually appear at the top of each list.
  • Now click **Save Configuration** then exit the program (using the ❎ at the upper right corner of the window or by clicking the ‘Quit’ button.""",

    "Usage": """• After restarting, select either the Area Search or Trailing Training Session tab. Using the mouse drag the window to a desired location on the screen and adjust the window dimensions (via using the mouse to resize it) to your satisfaction.  That placement and window size will be saved and used the next time the program is started.
  • Notice that some fields have white backgrounds while others are light grey. White fields can generally have free text entered while light-grey windows must use the dropdown by clicking the ˅ or ▼ on the right side of the entry. A few of the white entry fields also have a ˅ or ▼ for common entries. These entries can accept either text or selection via the dropdown menu.
  • **Start Time and Finish Time entries** – hover the mouse over the left half and rotate the mouse scroll wheel to change the hour.  Hover over the right side to adjust the minutes.  The time is recorded in 24-hour Military time to avoid confusion. Light grey in the time entry implies that no time is selected.  If a time is accidentally entered, double-click over the colon ‘:’ in that entry to unset it.
  • **Add Session Purpose **and** Session** **Purposes** – these are paired fields that can accumulate multiple training purposes. 
  • **Add Session Purpose** – selects one purpose at a time to be added to accumulated purposes.  Use either use the dropdown list or type in a custom purpose followed by **Enter**.
  • **Session Purposes** – is the list of all purposes of this training session.  If a purpose is added by mistake, simply double-click that entry to remove it.
  • **Add Terrain Type **and** Accumulated Terrains** behave in the same manner as the Session Purpose pair described above.""",

    "Area Search Session Specific Items": """On the Area Search Training Session Tab **Number of Subjects****,**** Subjects Found **and the table to the right of **Subjects Found** work in tandem.  Notice that ‘Subjects Found’ is disabled until the number of subjects is entered.  Once that is done select the number of subjects found which enables the table to the right.  For each subject found a single click under the heading ‘Indication on Initial Find’ or ‘Indication on Refind’ presents a dropdown box to fill in the dog’s action.""",

    "Trailing Session Specific Items": """On the Trailing Training Session tab find three linked entries in the box labeled **Distractions**. First, select the desired distraction, then select response. One can either use the dropdown list or type in a custom answer.  If typing a custom response, that entry must be registered by typing **Enter**.  Notice that the pair will then present in the **Accumulated Distractions** table.  If not satisfied with an entry, it can be selected by hovering over the desired entry and clicking the mouse. Note that the **Distraction** and **Response** fields list that entry and may now be edited. If only the **Distraction** entry is modified, click **Update** to register that change. Editing the **Response** updates automatically.""",

    "Miscellaneous Items": """**Images** – photos or maps or GoPro mp4 files can be added either by browsing to the desired file or using Windows drag and drop.
**View/Edit/Hide Prior Sessions(s)** – This can be useful if the user discovers that a prior session needs to be updated. Simply select a session or group of sessions to review.  If a session is to be updated, make the desired changes followed by clicking the **Update Session** button.  If more than one session is to be updated, click **View/Edit/Hide Prior Session(s)** again and select the session to update.
The user also has the ability to hide a session.  This function is in lieu of a delete function which would be permanent and could lead to irreversible data loss. When in view mode simply click **Hide**. To return a session to the active list hidden sessions can be selected from the View/Edit/Hide window using the radio buttons at the bottom of the form. Then simply click **Restore**.
**Export PDF** – generates human readable logs for review by team members or for certification. These documents are saved in the folder defined at setup time."""
}

# Index mapping terms to sections
HELP_INDEX = {
    "**Browse** button": ["Setup"],
    "backup folder": ["Setup"]
}


class HelpWindow:
    """A searchable help dialog with section navigation and index."""
    
    def __init__(self, parent):
        """
        Initialize the help window.
        
        Args:
            parent: Parent tkinter window
        """
        self.parent = parent
        self.window = None
    
    def show(self):
        """Show the help window (or bring existing window to front)."""
        # If window already exists, just bring it to front
        if self.window and self.window.winfo_exists():
            self.window.lift()
            self.window.focus_force()
            return
        
        # Create new window
        self.window = tk.Toplevel(self.parent)
        self.window.title("SAR K9 Training Record - User Manual")
        
        # Set window size and position (centered)
        window_width = 1000
        window_height = 700
        screen_width = self.window.winfo_screenwidth()
        screen_height = self.window.winfo_screenheight()
        x = (screen_width - window_width) // 2
        y = (screen_height - window_height) // 2
        self.window.geometry(f"{window_width}x{window_height}+{x}+{y}")
        self.window.minsize(800, 500)
        
        self.setup_ui()
        self.populate_sections()
        self.populate_index()
        
        # Select first section by default
        if self.section_listbox.size() > 0:
            self.section_listbox.selection_set(0)
            self.on_section_selected(None)
        
        # Bind Escape key to close
        self.window.bind("<Escape>", lambda e: self.window.destroy())
        
        # Bind F1 to close (toggle behavior)
        self.window.bind("<F1>", lambda e: self.window.destroy())
    
    def setup_ui(self):
        """Set up the user interface."""
        # Main container with padding
        main_frame = ttk.Frame(self.window, padding="10")
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Search bar at top
        search_frame = ttk.Frame(main_frame)
        search_frame.pack(fill=tk.X, pady=(0, 10))
        
        ttk.Label(search_frame, text="Search:").pack(side=tk.LEFT, padx=(0, 5))
        self.search_var = tk.StringVar()
        self.search_var.trace('w', self.filter_current_tab)
        self.search_entry = ttk.Entry(search_frame, textvariable=self.search_var, width=40)
        self.search_entry.pack(side=tk.LEFT, fill=tk.X, expand=True)
        
        # Paned window for left panel and content
        paned = ttk.PanedWindow(main_frame, orient=tk.HORIZONTAL)
        paned.pack(fill=tk.BOTH, expand=True, pady=(0, 10))
        
        # Left frame - notebook with Topics and Index tabs
        left_frame = ttk.Frame(paned)
        paned.add(left_frame, weight=1)
        
        self.notebook = ttk.Notebook(left_frame)
        self.notebook.pack(fill=tk.BOTH, expand=True)
        
        # Topics tab
        topics_frame = ttk.Frame(self.notebook)
        self.notebook.add(topics_frame, text="Topics")
        
        list_frame = ttk.Frame(topics_frame)
        list_frame.pack(fill=tk.BOTH, expand=True, pady=(5, 0))
        
        self.section_listbox = tk.Listbox(list_frame, width=30, font=('TkDefaultFont', 10))
        scrollbar = ttk.Scrollbar(list_frame, orient=tk.VERTICAL, command=self.section_listbox.yview)
        self.section_listbox.configure(yscrollcommand=scrollbar.set)
        
        self.section_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        
        self.section_listbox.bind('<<ListboxSelect>>', self.on_section_selected)
        
        # Index tab
        index_frame = ttk.Frame(self.notebook)
        self.notebook.add(index_frame, text="Index")
        
        index_list_frame = ttk.Frame(index_frame)
        index_list_frame.pack(fill=tk.BOTH, expand=True, pady=(5, 0))
        
        self.index_listbox = tk.Listbox(index_list_frame, width=30, font=('TkDefaultFont', 10))
        index_scrollbar = ttk.Scrollbar(index_list_frame, orient=tk.VERTICAL, command=self.index_listbox.yview)
        self.index_listbox.configure(yscrollcommand=index_scrollbar.set)
        
        self.index_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        index_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        
        self.index_listbox.bind('<<ListboxSelect>>', self.on_index_selected)
        
        # Right frame - content
        right_frame = ttk.Frame(paned)
        paned.add(right_frame, weight=3)
        
        # Content text widget with scrollbar
        content_frame = ttk.Frame(right_frame)
        content_frame.pack(fill=tk.BOTH, expand=True)
        
        self.content_text = tk.Text(
            content_frame, 
            wrap=tk.WORD, 
            font=('Arial', 12),
            padx=15,
            pady=10,
            bg="white",
            fg="black",
            state=tk.DISABLED
        )
        content_scrollbar = ttk.Scrollbar(content_frame, orient=tk.VERTICAL, command=self.content_text.yview)
        self.content_text.configure(yscrollcommand=content_scrollbar.set)
        
        self.content_text.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        content_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        
        # Configure text tags for formatting
        self.content_text.tag_configure('title', font=('Arial', 16, 'bold'), 
                                         foreground='#2c3e50', spacing3=10)
        self.content_text.tag_configure('heading2', font=('Arial', 14, 'bold'),
                                         foreground='#34495e', spacing1=15, spacing3=5)
        self.content_text.tag_configure('heading3', font=('Arial', 12, 'bold'),
                                         foreground='#7f8c8d', spacing1=10, spacing3=5)
        self.content_text.tag_configure('bold', font=('Arial', 12, 'bold'))
        self.content_text.tag_configure('italic', font=('Arial', 12, 'italic'))
        self.content_text.tag_configure('bolditalic', font=('Arial', 12, 'bold italic'))
        self.content_text.tag_configure('bullet', lmargin1=20, lmargin2=35)
        self.content_text.tag_configure('normal', spacing1=3, spacing3=3)
        self.content_text.tag_configure('link', foreground='#2980b9', underline=True)
        self.content_text.tag_configure('index_term', font=('Arial', 12, 'bold'),
                                         foreground='#2c3e50', spacing1=10)
        self.content_text.tag_configure('index_sections', lmargin1=20, foreground='#2980b9',
                                         underline=True)
        
        # Close button at bottom
        button_frame = ttk.Frame(main_frame)
        button_frame.pack(fill=tk.X)
        
        ttk.Button(button_frame, text="Close", command=self.window.destroy).pack(side=tk.RIGHT)
    
    def populate_sections(self):
        """Populate the section list with all help sections."""
        self.section_listbox.delete(0, tk.END)
        self.all_sections = list(HELP_SECTIONS.keys())
        for section_title in self.all_sections:
            self.section_listbox.insert(tk.END, section_title)
    
    def populate_index(self):
        """Populate the index list with all indexed terms."""
        self.index_listbox.delete(0, tk.END)
        self.all_index_terms = sorted(HELP_INDEX.keys(), key=str.lower)
        for term in self.all_index_terms:
            self.index_listbox.insert(tk.END, term)
    
    def on_section_selected(self, event):
        """Handle section selection change."""
        selection = self.section_listbox.curselection()
        if not selection:
            return
        
        section_title = self.section_listbox.get(selection[0])
        content = HELP_SECTIONS.get(section_title, "")
        
        self.display_content(section_title, content)
    
    def on_index_selected(self, event):
        """Handle index term selection - show sections containing this term."""
        selection = self.index_listbox.curselection()
        if not selection:
            return
        
        term = self.index_listbox.get(selection[0])
        sections = HELP_INDEX.get(term, [])
        
        self.display_index_entry(term, sections)
    
    def display_index_entry(self, term, sections):
        """Display an index entry with clickable section links."""
        self.content_text.configure(state=tk.NORMAL)
        self.content_text.delete(1.0, tk.END)
        
        # Insert term as title
        self.content_text.insert(tk.END, f"Index: {term}\n\n", 'title')
        
        self.content_text.insert(tk.END, "Found in:\n\n", 'normal')
        
        # Insert each section as a clickable link
        for section in sections:
            # Create a unique tag for this link
            link_tag = f"link_{section.replace(' ', '_')}"
            self.content_text.tag_configure(link_tag, foreground='#2980b9', underline=True)
            
            self.content_text.insert(tk.END, "  • ", 'normal')
            self.content_text.insert(tk.END, section, link_tag)
            self.content_text.insert(tk.END, "\n", 'normal')
            
            # Bind click event to this link
            self.content_text.tag_bind(link_tag, '<Button-1>', 
                                        lambda e, s=section: self.jump_to_section(s))
            self.content_text.tag_bind(link_tag, '<Enter>',
                                        lambda e: self.content_text.configure(cursor='hand2'))
            self.content_text.tag_bind(link_tag, '<Leave>',
                                        lambda e: self.content_text.configure(cursor=''))
        
        self.content_text.configure(state=tk.DISABLED)
    
    def jump_to_section(self, section_name):
        """Jump to a section from an index link."""
        # Switch to Topics tab
        self.notebook.select(0)
        
        # Find and select the section
        for i in range(self.section_listbox.size()):
            if self.section_listbox.get(i) == section_name:
                self.section_listbox.selection_clear(0, tk.END)
                self.section_listbox.selection_set(i)
                self.section_listbox.see(i)
                self.on_section_selected(None)
                break
    
    def display_content(self, title, content):
        """Display formatted content in the text widget."""
        self.content_text.configure(state=tk.NORMAL)
        self.content_text.delete(1.0, tk.END)
        
        # Insert title
        self.content_text.insert(tk.END, title + "\n\n", 'title')
        
        # Process content line by line
        lines = content.split('\n')
        for line in lines:
            if line.startswith('## '):
                # Heading 2
                self.content_text.insert(tk.END, line[3:] + "\n", 'heading2')
            elif line.startswith('### '):
                # Heading 3
                self.content_text.insert(tk.END, line[4:] + "\n", 'heading3')
            elif line.strip().startswith('•') or re.match(r'^\s*\d+\.', line):
                # Bullet or numbered list
                self.insert_formatted_text(line + "\n", 'bullet')
            elif line.strip():
                # Regular paragraph
                self.insert_formatted_text(line + "\n", 'normal')
            else:
                # Empty line
                self.content_text.insert(tk.END, "\n")
        
        self.content_text.configure(state=tk.DISABLED)
    
    def insert_formatted_text(self, text, base_tag):
        """Insert text with bold/italic formatting."""
        # Pattern to match **bold**, *italic*, and ***bolditalic***
        pattern = r'(\*\*\*.*?\*\*\*|\*\*.*?\*\*|\*.*?\*)'
        
        parts = re.split(pattern, text)
        for part in parts:
            if part.startswith('***') and part.endswith('***'):
                self.content_text.insert(tk.END, part[3:-3], ('bolditalic', base_tag))
            elif part.startswith('**') and part.endswith('**'):
                self.content_text.insert(tk.END, part[2:-2], ('bold', base_tag))
            elif part.startswith('*') and part.endswith('*') and len(part) > 2:
                self.content_text.insert(tk.END, part[1:-1], ('italic', base_tag))
            else:
                self.content_text.insert(tk.END, part, base_tag)
    
    def filter_current_tab(self, *args):
        """Filter the currently visible tab based on search text."""
        current_tab = self.notebook.index(self.notebook.select())
        if current_tab == 0:
            self.filter_sections()
        else:
            self.filter_index()
    
    def filter_sections(self, *args):
        """Filter sections based on search text."""
        search_text = self.search_var.get().lower()
        
        self.section_listbox.delete(0, tk.END)
        
        for section_title in self.all_sections:
            section_content = HELP_SECTIONS.get(section_title, "")
            
            # Show item if search text is in title or content
            if search_text in section_title.lower() or search_text in section_content.lower():
                self.section_listbox.insert(tk.END, section_title)
        
        # Select first visible item
        if self.section_listbox.size() > 0:
            self.section_listbox.selection_set(0)
            self.on_section_selected(None)
    
    def filter_index(self, *args):
        """Filter index based on search text."""
        search_text = self.search_var.get().lower()
        
        self.index_listbox.delete(0, tk.END)
        
        for term in self.all_index_terms:
            if search_text in term.lower():
                self.index_listbox.insert(tk.END, term)
        
        # Select first visible item
        if self.index_listbox.size() > 0:
            self.index_listbox.selection_set(0)
            self.on_index_selected(None)
    
    def show_section(self, section_name):
        """Show a specific section by name."""
        self.notebook.select(0)  # Switch to Topics tab
        for i in range(self.section_listbox.size()):
            if self.section_listbox.get(i) == section_name:
                self.section_listbox.selection_clear(0, tk.END)
                self.section_listbox.selection_set(i)
                self.section_listbox.see(i)
                self.on_section_selected(None)
                break


def show_help_window(parent):
    """
    Show the help window.
    
    Args:
        parent: Parent tkinter window
    """
    help_win = HelpWindow(parent)
    help_win.show()


if __name__ == "__main__":
    # Test the help window standalone
    root = tk.Tk()
    root.withdraw()  # Hide the root window
    
    help_win = HelpWindow(root)
    help_win.show()
    
    root.mainloop()
